### ISSUE TITLE
Timing seems slightly fast

### ISSUE THREAD

**Issue by Fauxbear95** [Loze-Put/hunllef-helper#15]
I could record an example if you'd like but I've noticed the timing slowly shift so eventually it's telling me to make a prayer switch too early which would result in me taking the 4th attack. It's a minor thing, I've taken to resetting the plugin mid-fight but it's less than ideal.

**Comment by Loze-Put** [comment]
The plugin uses 600ms as a single game tick. As long as your game is running at exactly that speed the plugin should work just fine. The issue occurs when the game server has a delay. It would be possible to update the timer based on the elapsed game ticks, but this would use game state for the plugin. I'm very hesitant to implement this because that would move the plugin even closer to the edge of being allowed/banned.

**Comment by Fauxbear95** [comment]
Ok, I'll make a switch to an emptier world and see if it makes a difference. Thanks for the timely reply.

**Comment by Fauxbear95** [comment]
It does seem to work better. Apparently I was just on a busy server
