### ISSUE TITLE
Custom sounds aren't working

### ISSUE THREAD

**Issue by AreGoose** [Loze-Put/hunllef-helper#41]
I did everything you told me to do but when I try to turn the plugin on again after turning it of, the sidebar panel doesn't show up. this is fixed by resetting but the custom sound don't work. the sound are the correct name and aren't longer than 1 second

**Comment by Loze-Put** [comment]
Hi,

Could you provide me with a RuneLite log file? This file can be found in the .runelite/logs folder. Any file starting with `client` of a date when you encountered the issue will do.

**Comment by AreGoose** [comment]
[client_2023-09-04.0.log](https://github.com/Loze-Put/hunllef-helper/files/12528066/client_2023-09-04.0.log)
here it is

**Comment by Loze-Put** [comment]
The log file indicates that your files have an invalid format. This is usually caused by renaming a files' extension instead of converting its format. If you had an original file with a different format (for instance `.mp3`) convert it to a `.wav` using am online file converter. Renaming the file extension will not work.
